Feature/devil onchange
odoo-brazil/l10n-brazil pull request #101
Opened 2020-05-08 10:56 UTC by hendrixcosta

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2020-05-10 10:50 UTC, mileo commented on l10n_br_fiscal/models/document_abstract.py
> +        for ifiscal_payment_temp_idsnvalid in invalids:
Typo

2020-05-12 12:27 UTC, mileo commented
@gabrielcardoso21

2020-05-12 13:24 UTC, gabrielcardoso21 requested changes

2020-05-12 13:24 UTC, gabrielcardoso21 commented on l10n_br_fiscal/views/document_view.xml
> -                        'default_amount': amount_missing_payment_value,
Só não entendi a substituição desse campo pelo amount_total. O campo continua existindo e seu cálculo sendo feito corretamente pelo que testei.

2020-05-12 13:28 UTC, hendrixcosta commented on l10n_br_fiscal/views/document_view.xml
> -                        'default_amount': amount_missing_payment_value,
@gabrielcardoso21 em uma das versões esse campo não estava sendo calculado corretamente. Eu estava minimizando os erros e substitui pelo amout_total..

Mas podemos voltar com esse campo, sem problemas..

2020-05-12 13:50 UTC, gabrielcardoso21 commented on l10n_br_fiscal/views/document_view.xml
> -                        'default_amount': amount_missing_payment_value,
Se não estava funcionando pode deixar o amount_total mesmo. O problema é só no caso de haver mais de um pagamento, que o usuário teria de tomar o cuidado de calcular o valor faltante do segundo pagamento e colocar esse valor na tela do pagamento.

2020-05-12 13:51 UTC, gabrielcardoso21 approved these changes

2020-05-12 13:52 UTC, hendrixcosta commented on l10n_br_fiscal/views/document_view.xml
> -                        'default_amount': amount_missing_payment_value,
Como já esta no pente ai, faz essse teste por favor..
E se der certo já faz o commit e boas
Valeu Gabriel!

2020-11-12 16:29 UTC, closed without merging