Imp/l10n br account payment order
odoo-brazil/l10n-brazil pull request #122
Opened 2021-04-11 08:42 UTC by mileo

2021-04-14 15:23 UTC, mbcosta commented on l10n_br_account_payment_order/constants.py
> +CODES_PAYMENT_ORDER = (
Acredito que é melhor definir essa constante com algo que identifique claramente que se trata dos códigos ligados ao CNAB ou se a intenção é englobar o PIX a casos de pagamento com registro em Bancos do Brasil ( ex.: CNAB_CODES_PAYMENT_ORDER, BR_CODES_PAYMENT_ORDER ), porque nos códigos onde isso está sendo usado com esse nome fica muito genérico e a implementação em teoria permite o funcionamento tanto de Ordens de Pagamento do Brasil quanto de outros países em uma mesma base de dados.

2021-04-14 15:36 UTC, mbcosta commented on l10n_br_account_payment_order/models/account_payment_line.py
> +            record.amount_interest = record.currency_id.round(
Algum motivo para deixar de usar a Precisão Decimal definida para o "Account" ? Até onde sei no caso de valores dos Bancos não é uma questão apenas de arredondamento há também uma questão que os Bancos trabalham com duas casas decimais, e quantidade de casas a serem usadas estaria definida na Precisão do "Account" e não no método "round" ou ao adicionar o "currency_id" isso já é considerado ?

2021-04-14 16:04 UTC, mbcosta commented on l10n_br_account_payment_order/models/account_payment_order.py
> +        if self.payment_method_id.code == CODE_MANUAL_TEST:
Acredito que deveria ser adicionado um comentário aqui explicando a função do codigo para os testes como foi feito aqui https://github.com/odoo-brazil/l10n-brazil/blob/imp/l10n_br_account_payment_order/l10n_br_account_payment_order/demo/account_payment_method.xml#L7

2021-04-14 16:05 UTC, mbcosta commented on l10n_br_account_payment_order/readme/ROADMAP.rst
> +
O arquivo está sendo alterado mas nada foi feito, faltou algo ?

2021-04-14 16:20 UTC, mbcosta commented on l10n_br_account_payment_order/tests/test_payment_order_change.py
> +
Seria importante nesse caso validar se foi feita a reconciliação e talvez os outro campos usados que devem ser alterados, veja um exemplo https://github.com/akretion/odoo-boleto-cnab/blob/12.0-integrate_account_move_base_import/l10n_br_account_payment_brcobranca/tests/test_payment_order.py#L369

2021-04-14 16:23 UTC, mbcosta commented on l10n_br_account_payment_order/wizards/account_payment_line_create.py
> +        # self.ensure_one()
Algum motivo para manter o código comentado ? Seria bom ter um TODO com a descrição do que falta ou o problema relacionado

2021-04-15 01:35 UTC, mileo commented on l10n_br_account_payment_order/models/account_payment_line.py
> +            record.amount_interest = record.currency_id.round(
O currency usa a precisão da moeda que também é dois no caso padrão do BRL.

Os dois funcionam na mesma forma, com o currency o código ficou mais limpo.

Mas ambos estão expostos a uma alteração indevida do usuário.

Talvez seja melhor deixar fixo, o que vc acha?

2021-04-15 01:40 UTC, mileo commented on l10n_br_account_payment_order/readme/ROADMAP.rst
> +
Eu ia colar lá mas ia ter que reescrever tudo, segue alguns itens que eu já mapeei:

![image](https://user-images.githubusercontent.com/1975978/114801599-628a5e80-9d72-11eb-8195-b310b235ed87.png)

2021-04-15 01:41 UTC, mileo commented on l10n_br_account_payment_order/tests/test_payment_order_change.py
> +
Sim, vou dar uma olhada nesses asserts com calma.

2021-04-15 01:43 UTC, mileo commented on l10n_br_account_payment_order/wizards/account_payment_line_create.py
> +        # self.ensure_one()
Estou reestruturando o método, no fim só vai sobrar isso:

```
        move_line_domain = ["draft"]
        if self.allow_error:
            move_line_domain.append("exporting_error")
        if self.allow_rejected:
            move_line_domain.append("not_accepted")

        domain += [("bank_payment_line_id", "=", False)]

        domain += [("state_cnab", "in", move_line_domain)]
 ```

Mas estava testando com eles e estava dando problema, ai acabei comentando método.

2021-04-15 02:03 UTC, mileo commented
@mbcosta obrigado pela revisão, hoje não consegui trabalhar muito pois fui no oftalmologista e fiquei com a pupila dilatada boa parte do dia. Mas amanhã vou trabalhar nos itens da lista postada acima.

2021-04-29 19:15 UTC, mbcosta commented on l10n_br_account_payment_order/models/account_payment_line.py
> +            record.amount_interest = record.currency_id.round(
Se o currency pode ter uma precisão e o Account outra, acredito que o melhor é manter o Account porque acredito que é essa a precisão decimal que está sendo usada em outros campos de casos semelhantes( talvez podem existir parametrizações distintas entre o currency e o Account dependendo da empresa ? Não sei dizer ). Sou contra fixar variável, acredito que no máximo podemos colocar um aviso a respeito mas não bloquear, sobre alterações indevidas até onde sei por padrão o usuário que tem acesso para alterar é o admin e nesse caso a responsabilidade e de quem está implementando ou quem possui esse acesso nos não temos como ser responsáveis ou mesmo prever o uso de uma implementação de terceiros.

cc @renatonlima

2021-04-29 20:30 UTC, mbcosta commented on l10n_br_account_payment_order/readme/ROADMAP.rst
> +
* Reenvio de registros com erro através do wizard - acredito que esse seria o caso onde a Instrução do CNAB foi rejeitada e seria preciso corrigir uma informação de cadastro da empresa e reenviar as linhas rejeitadas em uma nova Ordem de Pagto, aparentemente isso teria que ser resolvido com um botão na account.invoice com algo como "Reenviar CNAB" onde teria que validar a questão de não estar aguardando o retorno do Banco de uma tentativa anterior e seria chamado o mesmo metodo de create_payment_line mantendo o histórico dos campos do Payment Line e Return CNAB LOG, seria isso ?

*  Criar um Boleto a partir de uma AML s/ invoice e importar através do wizard - acredito que esse é o caso "Exemplo: Um e-commerce pode emitir um boleto s/ uma fatura, após o pagamento é feito o faturamento" esse processo deveria ser melhor avaliado, porque é possível criar tanto um Nota de Credito quanto de Debito para isso, a ideia de ter uma AML avulsa não parece ser a melhor forma de implementar isso, talvez o ideal seja gerar um Pedido de Venda onde é gerada uma Nota de Credito e depois se paga gera a outra Nota

* Ao remover uma linha de uma ordem de pagamento, ela deve ser considerada a enviar novamente - na verdade deveria ser possível excluir uma linha da ordem de pagto ? Parece que não, porque isso vai ficar sem registro, esse processo deve ser melhor detalhado

* Validar a escrita do cnab_state - o campo deve ser readonly e ser alterado apenas dentro dos métodos, seria isso ?

* account_move -> update_cnab_for_cancel_invoice - não entendi esse item, o que seria ?

* RETORNO Lote 100% aceito - o que deveria ser feito além de criar um LOG de Retorno CNAB e alterar o cnab_state das AMLs para accept ?

* RETORNO Lote aceito Parcial -  o que deveria ser feito além de criar um LOG de Retorno CNAB e alterar o cnab_state das AMLs para accept ou not_accepted ?

* RETORNO Alteração aceita - o que deveria ser feito além de criar um LOG de Retorno CNAB e alterar o cnab_state das AMLs para accept ?

*  RETORNO Alteração não aceita - o que deveria ser feito além de criar um LOG de Retorno CNAB e alterar o cnab_state das AMLs para accept ou not_accepted ?

* RETORNO Liquidação , RETORNO Liquidação com desconto, RETORNO Liquidação com juros -  hoje o método referente a esse processo não está no modulo l10n_br_account_payment_order, deveria ? Se sim vocês precisam avaliar o que foi feito no l10n_br_account_payment_brcobranca para saber se temos consenso, o que está sendo feito hoje nesse caso é a criação de uma account.move para cada linha de CNAB com uma linha referente a reconciliação onde o valor informado é ( Valor Liquido + Valor da Tarifa + Valor do Desconto + Valor do Abatimento ) - Valor de Juros e para cada Valor de Tarifa, Juros, Desconto e Abatimento são criados dois lançamentos Contábeis de Credito e Debito, no caso de Desconto, Abatimento e Tarifa a Conta de Debito é a conta contábil informada no Modo de Pagto e a de Credito é a Conta Contabil padrão de Credito do Diário Contábil que está sendo usado na importação no caso do Juros a Conta de  Debito é a Conta Contabil padrão de Debito do Diário Contábil que está sendo usado e a de Credito e a do Modo de Pagto, portanto o que deveria ser o ROADMAP nesse caso ? 

* Melhorar o assert dos tests - bom acredito que isso serve para todos os módulos, idealmente deveria sempre ser 100% de cobertura, não sei dizer se isso deveria estar no ROADMAP já que serve para todos

2021-04-29 20:34 UTC, mbcosta commented on l10n_br_account_payment_order/wizards/account_payment_line_create.py
> +        # self.ensure_one()
Seria melhor resolver essa questão de código comentado removendo, corrigindo, ou colocando um TODO referente ao problema para que os outros desenvolvedores saibam do que se trata antes do merge.

2021-05-03 19:47 UTC, renatonlima requested changes

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +        string='Valor do Abatimento',
Esses campos deveria um fields.Monetary()

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +    amount_interest = fields.Float(
Esse campo deveria ser um fields.Monetary()

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +    discount_value = fields.Float(
Esse campo deveria ser um fields.Monetary()

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +    interest_value = fields.Float(
Esse campo deveria ser um fields.Monetary()

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +    fee_value = fields.Float(
Esse campo deveria ser um fields.Monetary()

2021-05-03 19:47 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +        default=0.00,
Não é necessário esse default e isso gera um problema de performace https://github.com/OCA/l10n-brazil/pull/1107

2021-05-03 20:02 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +            record.amount_interest = record.currency_id.round(
A maior parte dos valores do Odoo hoje usa o Monetary que no banco de dados fica com o tipo decimal, a precisão decimal do account deveria ser usada nos campos valores do account.move.line. o restante deveria usar a precisão decimal da moeda e os campos com valores financeiros deveriam ficar como fields.Monetary()

2021-05-04 21:07 UTC, merged

2021-05-05 02:14 UTC, mileo commented
=D